rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - jruby-19mode
  - jruby-head
  - rbx-2
  - ruby-head
  - ree

script: "bundle exec rake spec"

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: 1.8.7
    - rvm: ree
    - rvm: ruby-head

sudo: false

notifications:
  webhooks: http://td-beda.herokuapp.com/travisci_callback
