rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - rbx-2
  - ruby-head
  - ree

script: "bundle exec rake spec"

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: 1.8.7
    - rvm: ree

sudo: false

notifications:
  webhooks: http://td-beda.herokuapp.com/travisci_callback
