rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - jruby-19mode
  - jruby-9.2.4.0
  - jruby-head
  - ruby-head

script: "bundle exec rake spec"

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

sudo: false

notifications:
  webhooks: http://td-beda.herokuapp.com/travisci_callback
