rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - jruby-9.0.5.0
  - jruby-head
  - rbx-2
  - ruby-head

script: "bundle exec rake spec"

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby-head

sudo: false

notifications:
  webhooks: http://td-beda.herokuapp.com/travisci_callback
