---
version: "{build}"
clone_depth: 10
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - bundle --version
  - bundle install
build_script:
  - bundle exec rake build
test_script:
  - bundle exec rake spec
environment:
  matrix:
    - ruby_version: "21"
    - ruby_version: "22"
    - ruby_version: "23"
