# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "td-client"
  s.version = "0.8.41"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sadayuki Furuhashi"]
  s.date = "2013-01-09"
  s.extra_rdoc_files = [
    "ChangeLog",
    "README.rdoc"
  ]
  s.files = [
    "data/ca-bundle.crt",
    "lib/td-client.rb",
    "lib/td/client.rb",
    "lib/td/client/api.rb",
    "lib/td/client/compat_gzip_reader.rb",
    "lib/td/client/model.rb",
    "lib/td/client/version.rb",
    "spec/api_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Treasure Data API library for Ruby"
  s.test_files = ["spec/api_spec.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<msgpack>, ["~> 0.4.4"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
    else
      s.add_dependency(%q<msgpack>, ["~> 0.4.4"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    end
  else
    s.add_dependency(%q<msgpack>, ["~> 0.4.4"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
  end
end

