version: 2.1


orbs:
  ruby: circleci/ruby@1.1.2 


commands:
  bundle-install:
    description: "Install dependencies"
    steps:
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Bundle install
          command: bundle install
  run-tests:
    description: "Run tests"
    steps:
      - run:
          name: Run tests
          command: bundle exec rake spec
  run-tests-flow:
    description: "Single flow for running tests"
    steps:
      - checkout
      - bundle-install
      - run-tests


jobs:

  ruby_21:
    docker:
      - image: circleci/ruby:2.1.10
    executor: ruby/default
    steps:
      - run-tests-flow

  ruby_22:
    docker:
      - image: circleci/ruby:2.2.10
    executor: ruby/default
    steps:
      - run-tests-flow

  ruby_23:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - ruby/install:
          version: '2.3'
      - run-tests-flow

  ruby_24:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - run:
          name: Workaround for missing SSLv3 method
          command: rvm pkg install openssl && rvm install 2.4 --with-openssl-dir=$rvm_path/usr && rvm use 2.4 && echo . $(rvm 2.4 do rvm env --path) >> $BASH_ENV
      - run-tests-flow

  ruby_25:
    docker:
      - image: circleci/ruby:2.5.8-stretch
    executor: ruby/default
    steps:
      - run-tests-flow

  ruby_26:
    docker:
      - image: circleci/ruby:2.6.6-stretch
    executor: ruby/default
    steps:
      - run-tests-flow

  ruby_27:
    docker:
      - image: circleci/ruby:2.7.2
    executor: ruby/default
    steps:
      - run-tests-flow

  ruby_30:
    docker:
      - image: circleci/ruby:3.0.0
    executor: ruby/default
    steps:
      - run-tests-flow
  
  jruby_latest:
    docker:
      - image: circleci/jruby:latest
    steps: 
      - run-tests-flow

workflows:
  tests:
    jobs:
      - ruby_21
      - ruby_22
      - ruby_23
      - ruby_24
      - ruby_25
      - ruby_26
      - ruby_27
      - ruby_30
      - jruby_latest
